import type { IsoTimestamp } from "@/platform/clock";
import type { CertificationId } from "@/modules/certifications/domain/certification";
import type { GenerationMode } from "@/modules/question-bank/domain/question";

/**
 * Generation-run aggregate: the record of one request to a language model
 * (`SPEC.md` section 10.3).
 *
 * A run is the single place provenance lives. An item generated by a run carries
 * that run's identifier and nothing else, so the model, persona, and template
 * that produced it are stated once and cannot drift between the run and its
 * items (`spec/AI-GUIDELINES.md` section 1.2).
 *
 * Domain code is framework-free: no React, Next.js, database driver, AWS SDK, or
 * environment access.
 */

export type GenerationRunId = string;

/**
 * The provider name the built-in test gateway records.
 *
 * Named here, in the domain, because `modelProvider` is provenance: a run row says
 * which provider wrote its items, and "was this real?" is a question about that
 * recorded value rather than about how the application happens to be configured
 * right now. The gateway, the composition root, and the screens that warn about
 * placeholder output all read the same constant, so none of them can disagree.
 */
export const FAKE_MODEL_PROVIDER = "fake";

/**
 * Whether a provider name means "nothing was actually generated".
 *
 * A predicate rather than an equality check at each call site, so the screens that
 * warn the owner do not have to know the spelling.
 */
export function isFakeModelProvider(provider: string): boolean {
  return provider === FAKE_MODEL_PROVIDER;
}

/**
 * What a run was asked to produce. One kind per run.
 *
 * `ENRICH_VOCABULARY` is the odd one out and deliberately so: it creates no new
 * items, it appends a revision to vocabulary cards the owner already has. It is
 * still a run rather than a separate concept because everything a run exists for
 * applies unchanged — a model was called, tokens were spent, output was validated,
 * per-item outcomes were counted, and the result needs a page the owner can read.
 * A parallel "enrichment run" table would duplicate all of that.
 *
 * `QUESTION_REVIEW` is the odd one out in the opposite direction: it produces no item
 * and proposes no item, it produces a *judgement* about an item the owner already has.
 * It is still a run because a model was called, tokens were spent, output was
 * validated, and the result needs to be readable months later beside the question it
 * was about (`spec/AI-GUIDELINES.md` section 1.10).
 *
 * `TUTOR_EXPLANATION` is the second kind that judges nothing and writes nothing: a model
 * was asked one thing about one revision — explain the answer, explain a wrong choice,
 * explain it more simply — and its answer is tutoring the owner reads. It is a run for
 * the same reasons a review is: a model was called, tokens were spent, output was
 * validated, and the exchange has to be readable later beside the question it was about.
 * It is *separate* from `QUESTION_REVIEW` because the two say different things about the
 * same question — a review is a judgement the owner may act on, an explanation is
 * teaching — and collapsing them would put explanations in the findings panel.
 */
/*
 * `ANSWER_EVALUATION` is the first kind whose subject is something the *owner* wrote rather
 * than something in their bank: a model is shown one short-answer question and the answer
 * the owner typed in a session, and says which of the expected concepts the answer covered.
 * It writes nothing — not the question, and deliberately not the attempt either. The
 * attempt keeps the owner's own `SELF_ASSESSED` verdict and this run records what the model
 * thought of it, which is the whole design (`domain/answer-evaluation.ts`).
 *
 * `QUESTION_CHALLENGE` is the third kind that judges an existing question, and it is
 * separate from `QUESTION_REVIEW` because the question it answers is different: a review
 * decides for itself what to look at, while a challenge adjudicates one specific objection
 * the owner raised. Collapsing the two would lose which of them a recorded run actually
 * was, and the challenge's outcome — a verdict about the owner's reading, plus a note about
 * what a revision would change — does not fit a review's findings.
 */
export type GeneratedItemKind =
  | "QUESTION"
  | "FLASHCARD"
  | "ENRICH_VOCABULARY"
  | "OBJECTIVE_IMPORT"
  | "QUESTION_REVIEW"
  | "TUTOR_EXPLANATION"
  | "ANSWER_EVALUATION"
  | "QUESTION_CHALLENGE";

export const GENERATED_ITEM_KINDS: readonly GeneratedItemKind[] = [
  "QUESTION",
  "FLASHCARD",
  "ENRICH_VOCABULARY",
  "OBJECTIVE_IMPORT",
  "QUESTION_REVIEW",
  "TUTOR_EXPLANATION",
  "ANSWER_EVALUATION",
  "QUESTION_CHALLENGE",
];

/**
 * Whether a run only *proposes* something the owner has still to confirm.
 *
 * `OBJECTIVE_IMPORT` is the only such kind so far, and it is the reason the run row
 * carries `proposedPayload` and `appliedAt`: a question run's output is in the bank
 * the moment the run completes, while an import run's output is a suggestion until
 * the owner applies it. A predicate rather than an equality check at each call site,
 * so the review screen, the repository, and the facade agree.
 */
export function proposesForConfirmation(kind: GeneratedItemKind): boolean {
  switch (kind) {
    case "QUESTION":
    case "FLASHCARD":
    case "ENRICH_VOCABULARY":
    // A review's payload is not a proposal awaiting an Apply. It is a finding the owner
    // reads; acting on it means disputing or approving the *question*, which is the
    // question's own action and leaves `applied_at` null forever.
    case "QUESTION_REVIEW":
    // Nor is a tutor's answer. It is read, not applied: nothing in it is waiting to be
    // written into the bank, including the follow-up question, which is deliberately
    // ephemeral tutoring content rather than a draft (`tutor-exchange.ts`).
    case "TUTOR_EXPLANATION":
    // Nor is a grading. It is advice the owner reads beside the verdict they recorded
    // themselves; there is nothing in it waiting to be written anywhere
    // (`answer-evaluation.ts`).
    case "ANSWER_EVALUATION":
    // Nor is a challenge outcome, including its revision note. The note says what a new
    // revision would have to change; writing that revision is the owner's own edit, which
    // is the point (`spec/AI-GUIDELINES.md` section 1.10).
    case "QUESTION_CHALLENGE":
      return false;
    case "OBJECTIVE_IMPORT":
      return true;
  }
}

/**
 * Whether a run rewrites existing items rather than creating them.
 *
 * A predicate on the kind rather than a check spelled out at each call site, so
 * the review screen, the repository, and the facade agree about which runs own
 * their items and which only touched them.
 */
export function revisesExistingItems(kind: GeneratedItemKind): boolean {
  switch (kind) {
    case "QUESTION":
    case "FLASHCARD":
    // An import run touches no bank item at all: it proposes objectives, which are
    // the track's outline rather than its content.
    case "OBJECTIVE_IMPORT":
    // A review reads one item and writes none. It may change the question's *quality
    // status*, which is a judgement about the item rather than a revision of it.
    case "QUESTION_REVIEW":
    // A tutor answer changes nothing at all about the question, not even its quality
    // state: explaining something is not a judgement about it.
    case "TUTOR_EXPLANATION":
    // A grading reads one attempt and one question and revises neither.
    case "ANSWER_EVALUATION":
    // A challenge judges one revision and never appends another. The owner does that.
    case "QUESTION_CHALLENGE":
      return false;
    case "ENRICH_VOCABULARY":
      return true;
  }
}

/**
 * Run status.
 *
 * `PARTIAL` exists because a batch is not all-or-nothing: a model can return ten
 * items of which eight are usable, and discarding the eight would waste a call
 * the owner paid for while hiding that the other two were rejected. `FAILED`
 * covers both "the provider call failed" and "nothing survived validation".
 */
export type GenerationRunStatus =
  "PENDING" | "COMPLETED" | "PARTIAL" | "FAILED";

export const GENERATION_RUN_STATUSES: readonly GenerationRunStatus[] = [
  "PENDING",
  "COMPLETED",
  "PARTIAL",
  "FAILED",
];

/**
 * Token counts as reported by the provider, when it reports them.
 *
 * Deliberately narrow: only counts. Nothing derived from credentials, request
 * signing, or account identity may be stored in run metadata
 * (`SPEC.md` section 10.3).
 */
export interface ProviderUsage {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly totalTokens: number;
}

/**
 * Why a run failed, in owner-facing terms.
 *
 * A category rather than a provider message, because the provider's text can
 * carry account identifiers, request ids, and model payloads that must not reach
 * the interface or the log (`spec/SECURITY.md`).
 */
export type GenerationFailureCategory =
  | "PROVIDER_UNAVAILABLE"
  | "PROVIDER_THROTTLED"
  | "PROVIDER_REJECTED_REQUEST"
  | "NOT_AUTHORIZED"
  | "MODEL_ACCESS_DENIED"
  | "TIMED_OUT"
  | "MALFORMED_OUTPUT"
  | "NO_USABLE_ITEMS"
  | "UNEXPECTED";

export const GENERATION_FAILURE_CATEGORIES: readonly GenerationFailureCategory[] =
  [
    "PROVIDER_UNAVAILABLE",
    "PROVIDER_THROTTLED",
    "PROVIDER_REJECTED_REQUEST",
    "NOT_AUTHORIZED",
    "MODEL_ACCESS_DENIED",
    "TIMED_OUT",
    "MALFORMED_OUTPUT",
    "NO_USABLE_ITEMS",
    "UNEXPECTED",
  ];

export interface GenerationRun {
  readonly id: GenerationRunId;
  readonly certificationId: CertificationId;
  readonly itemKind: GeneratedItemKind;
  readonly generationMode: GenerationMode;
  readonly modelProvider: string;
  readonly modelId: string;
  readonly personaId: string;
  readonly personaVersion: number;
  readonly promptTemplateId: string;
  readonly promptTemplateVersion: number;
  /**
   * Fingerprint of the request that produced this run, so an equivalent batch
   * can be recognised before it is generated again (`SPEC.md` section 11.6).
   */
  readonly inputHash: string;
  /** Always empty in D6: model-knowledge generation has no sources. */
  readonly selectedSourceSnapshotIds: readonly string[];
  readonly requestedItemCount: number;
  readonly successfulItemCount: number;
  readonly failedItemCount: number;
  readonly usageMetadata: ProviderUsage | null;
  readonly failureReason: GenerationFailureCategory | null;
  /**
   * What an `OBJECTIVE_IMPORT` run proposed, as validated JSON text.
   *
   * Text rather than a parsed tree because this type is the run *record*: the run
   * knows it is carrying a proposal and how big it is, and the shape of the proposal
   * belongs to whatever kind of run made it. The application parses it through a
   * schema when it needs the tree (`objective-import.ts`), so a hand-edited row
   * fails loudly instead of reaching the objective hierarchy.
   *
   * `null` for every other kind, and for an import run that failed.
   */
  readonly proposedPayload: string | null;
  /**
   * When the proposal was applied, for the run kinds that have one.
   *
   * `null` means "not applied", which is the whole idempotence guard: a second apply
   * is refused by reading this column rather than by trusting the page that posted.
   */
  readonly appliedAt: IsoTimestamp | null;
  /**
   * The question a `QUESTION_REVIEW` run judged.
   *
   * On the run row because a review is *about* one item, and without that the stored
   * findings would be a paragraph about nothing. `null` for every other kind, and
   * `null` once the question has been deleted — a run is historical and survives what
   * it looked at, rather than keeping a deletable draft alive.
   */
  readonly subjectQuestionId: string | null;
  /**
   * The exact revision the review was shown.
   *
   * Recorded separately from the question because a revision is immutable and a
   * question is not: the finding applies to *this wording*, and an edit afterwards
   * makes the review stale rather than wrong (`SPEC.md` section 25.3, "the tutor
   * receives the exact revision being discussed").
   */
  readonly subjectRevisionId: string | null;
  readonly startedAt: IsoTimestamp;
  readonly completedAt: IsoTimestamp | null;
  readonly status: GenerationRunStatus;
}

export function describeItemKind(kind: GeneratedItemKind): string {
  switch (kind) {
    case "QUESTION":
      return "Questions";
    case "FLASHCARD":
      return "Flashcards";
    case "ENRICH_VOCABULARY":
      return "Enriched vocabulary";
    case "OBJECTIVE_IMPORT":
      return "Imported objectives";
    case "QUESTION_REVIEW":
      return "AI question review";
    case "TUTOR_EXPLANATION":
      return "AI tutor answer";
    case "ANSWER_EVALUATION":
      return "AI answer grading";
    case "QUESTION_CHALLENGE":
      return "AI question challenge";
  }
}

export function describeItemKindSingular(kind: GeneratedItemKind): string {
  switch (kind) {
    case "QUESTION":
      return "question";
    case "FLASHCARD":
      return "flashcard";
    case "ENRICH_VOCABULARY":
      return "enriched card";
    case "OBJECTIVE_IMPORT":
      return "proposed objective";
    case "QUESTION_REVIEW":
      return "reviewed question";
    case "TUTOR_EXPLANATION":
      return "tutor answer";
    case "ANSWER_EVALUATION":
      return "graded answer";
    case "QUESTION_CHALLENGE":
      return "challenged question";
  }
}

export function describeRunStatus(status: GenerationRunStatus): string {
  switch (status) {
    case "PENDING":
      return "In progress";
    case "COMPLETED":
      return "Completed";
    case "PARTIAL":
      return "Partly completed";
    case "FAILED":
      return "Failed";
  }
}

/**
 * Owner-facing explanation of a failure category.
 *
 * Every category has a sentence saying what to do about it, because a failed run
 * that only says "failed" leaves the owner guessing whether to retry, change the
 * request, or fix their configuration.
 */
export function describeFailureCategory(
  category: GenerationFailureCategory,
): string {
  switch (category) {
    case "PROVIDER_UNAVAILABLE":
      return "The model provider could not be reached. Check your network and try again.";
    case "PROVIDER_THROTTLED":
      return "The model provider is rate limiting requests. Wait a moment and try a smaller batch.";
    case "PROVIDER_REJECTED_REQUEST":
      return "The model provider rejected the request. Try a smaller batch or shorter instructions.";
    case "NOT_AUTHORIZED":
      return "The configured credentials were not accepted. Check the AWS profile or role this application runs with.";
    case "MODEL_ACCESS_DENIED":
      return "This account cannot use the configured model in this region. Request model access in the Bedrock console.";
    case "TIMED_OUT":
      return "The request took too long and was abandoned. Try a smaller batch.";
    case "MALFORMED_OUTPUT":
      return "The model did not return usable structured output, including after one repair attempt.";
    case "NO_USABLE_ITEMS":
      return "Every generated item failed validation, so nothing was saved.";
    case "UNEXPECTED":
      return "Generation stopped for an unexpected reason. Nothing was saved.";
  }
}

/**
 * The status a finished run should carry.
 *
 * One function so the run row, the review screen, and the tests cannot disagree
 * about what "partial" means.
 */
export function resolveRunStatus(counts: {
  readonly successfulItemCount: number;
  readonly failedItemCount: number;
}): Exclude<GenerationRunStatus, "PENDING"> {
  if (counts.successfulItemCount === 0) {
    return "FAILED";
  }

  return counts.failedItemCount === 0 ? "COMPLETED" : "PARTIAL";
}
