import type { IsoTimestamp } from "@/platform/clock";
import type { CertificationId } from "@/modules/certifications/domain/certification";
import type { GenerationMode } from "@/modules/question-bank/domain/question";

/**
 * Generation-run aggregate: the record of one request to a language model
 * (`SPEC.md` section 10.3).
 *
 * A run is the single place provenance lives. An item generated by a run carries
 * that run's identifier and nothing else, so the model, persona, and template
 * that produced it are stated once and cannot drift between the run and its
 * items (`spec/AI-GUIDELINES.md` section 1.2).
 *
 * Domain code is framework-free: no React, Next.js, database driver, AWS SDK, or
 * environment access.
 */

export type GenerationRunId = string;

/** What a run was asked to produce. One kind per run. */
export type GeneratedItemKind = "QUESTION" | "FLASHCARD";

export const GENERATED_ITEM_KINDS: readonly GeneratedItemKind[] = [
  "QUESTION",
  "FLASHCARD",
];

/**
 * Run status.
 *
 * `PARTIAL` exists because a batch is not all-or-nothing: a model can return ten
 * items of which eight are usable, and discarding the eight would waste a call
 * the owner paid for while hiding that the other two were rejected. `FAILED`
 * covers both "the provider call failed" and "nothing survived validation".
 */
export type GenerationRunStatus =
  "PENDING" | "COMPLETED" | "PARTIAL" | "FAILED";

export const GENERATION_RUN_STATUSES: readonly GenerationRunStatus[] = [
  "PENDING",
  "COMPLETED",
  "PARTIAL",
  "FAILED",
];

/**
 * Token counts as reported by the provider, when it reports them.
 *
 * Deliberately narrow: only counts. Nothing derived from credentials, request
 * signing, or account identity may be stored in run metadata
 * (`SPEC.md` section 10.3).
 */
export interface ProviderUsage {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly totalTokens: number;
}

/**
 * Why a run failed, in owner-facing terms.
 *
 * A category rather than a provider message, because the provider's text can
 * carry account identifiers, request ids, and model payloads that must not reach
 * the interface or the log (`spec/SECURITY.md`).
 */
export type GenerationFailureCategory =
  | "PROVIDER_UNAVAILABLE"
  | "PROVIDER_THROTTLED"
  | "PROVIDER_REJECTED_REQUEST"
  | "NOT_AUTHORIZED"
  | "MODEL_ACCESS_DENIED"
  | "TIMED_OUT"
  | "MALFORMED_OUTPUT"
  | "NO_USABLE_ITEMS"
  | "UNEXPECTED";

export const GENERATION_FAILURE_CATEGORIES: readonly GenerationFailureCategory[] =
  [
    "PROVIDER_UNAVAILABLE",
    "PROVIDER_THROTTLED",
    "PROVIDER_REJECTED_REQUEST",
    "NOT_AUTHORIZED",
    "MODEL_ACCESS_DENIED",
    "TIMED_OUT",
    "MALFORMED_OUTPUT",
    "NO_USABLE_ITEMS",
    "UNEXPECTED",
  ];

export interface GenerationRun {
  readonly id: GenerationRunId;
  readonly certificationId: CertificationId;
  readonly itemKind: GeneratedItemKind;
  readonly generationMode: GenerationMode;
  readonly modelProvider: string;
  readonly modelId: string;
  readonly personaId: string;
  readonly personaVersion: number;
  readonly promptTemplateId: string;
  readonly promptTemplateVersion: number;
  /**
   * Fingerprint of the request that produced this run, so an equivalent batch
   * can be recognised before it is generated again (`SPEC.md` section 11.6).
   */
  readonly inputHash: string;
  /** Always empty in D6: model-knowledge generation has no sources. */
  readonly selectedSourceSnapshotIds: readonly string[];
  readonly requestedItemCount: number;
  readonly successfulItemCount: number;
  readonly failedItemCount: number;
  readonly usageMetadata: ProviderUsage | null;
  readonly failureReason: GenerationFailureCategory | null;
  readonly startedAt: IsoTimestamp;
  readonly completedAt: IsoTimestamp | null;
  readonly status: GenerationRunStatus;
}

export function describeItemKind(kind: GeneratedItemKind): string {
  switch (kind) {
    case "QUESTION":
      return "Questions";
    case "FLASHCARD":
      return "Flashcards";
  }
}

export function describeItemKindSingular(kind: GeneratedItemKind): string {
  switch (kind) {
    case "QUESTION":
      return "question";
    case "FLASHCARD":
      return "flashcard";
  }
}

export function describeRunStatus(status: GenerationRunStatus): string {
  switch (status) {
    case "PENDING":
      return "In progress";
    case "COMPLETED":
      return "Completed";
    case "PARTIAL":
      return "Partly completed";
    case "FAILED":
      return "Failed";
  }
}

/**
 * Owner-facing explanation of a failure category.
 *
 * Every category has a sentence saying what to do about it, because a failed run
 * that only says "failed" leaves the owner guessing whether to retry, change the
 * request, or fix their configuration.
 */
export function describeFailureCategory(
  category: GenerationFailureCategory,
): string {
  switch (category) {
    case "PROVIDER_UNAVAILABLE":
      return "The model provider could not be reached. Check your network and try again.";
    case "PROVIDER_THROTTLED":
      return "The model provider is rate limiting requests. Wait a moment and try a smaller batch.";
    case "PROVIDER_REJECTED_REQUEST":
      return "The model provider rejected the request. Try a smaller batch or shorter instructions.";
    case "NOT_AUTHORIZED":
      return "The configured credentials were not accepted. Check the AWS profile or role this application runs with.";
    case "MODEL_ACCESS_DENIED":
      return "This account cannot use the configured model in this region. Request model access in the Bedrock console.";
    case "TIMED_OUT":
      return "The request took too long and was abandoned. Try a smaller batch.";
    case "MALFORMED_OUTPUT":
      return "The model did not return usable structured output, including after one repair attempt.";
    case "NO_USABLE_ITEMS":
      return "Every generated item failed validation, so nothing was saved.";
    case "UNEXPECTED":
      return "Generation stopped for an unexpected reason. Nothing was saved.";
  }
}

/**
 * The status a finished run should carry.
 *
 * One function so the run row, the review screen, and the tests cannot disagree
 * about what "partial" means.
 */
export function resolveRunStatus(counts: {
  readonly successfulItemCount: number;
  readonly failedItemCount: number;
}): Exclude<GenerationRunStatus, "PENDING"> {
  if (counts.successfulItemCount === 0) {
    return "FAILED";
  }

  return counts.failedItemCount === 0 ? "COMPLETED" : "PARTIAL";
}
