import type { IsoTimestamp } from "@/platform/clock";
import type { CertificationId } from "@/modules/certifications/domain/certification";
import type { GenerationMode } from "@/modules/question-bank/domain/question";

/**
 * Generation-run aggregate: the record of one request to a language model
 * (`SPEC.md` section 10.3).
 *
 * A run is the single place provenance lives. An item generated by a run carries
 * that run's identifier and nothing else, so the model, persona, and template
 * that produced it are stated once and cannot drift between the run and its
 * items (`spec/AI-GUIDELINES.md` section 1.2).
 *
 * Domain code is framework-free: no React, Next.js, database driver, AWS SDK, or
 * environment access.
 */

export type GenerationRunId = string;

/**
 * The provider name the built-in test gateway records.
 *
 * Named here, in the domain, because `modelProvider` is provenance: a run row says
 * which provider wrote its items, and "was this real?" is a question about that
 * recorded value rather than about how the application happens to be configured
 * right now. The gateway, the composition root, and the screens that warn about
 * placeholder output all read the same constant, so none of them can disagree.
 */
export const FAKE_MODEL_PROVIDER = "fake";

/**
 * Whether a provider name means "nothing was actually generated".
 *
 * A predicate rather than an equality check at each call site, so the screens that
 * warn the owner do not have to know the spelling.
 */
export function isFakeModelProvider(provider: string): boolean {
  return provider === FAKE_MODEL_PROVIDER;
}

/**
 * What a run was asked to produce. One kind per run.
 *
 * `ENRICH_VOCABULARY` is the odd one out and deliberately so: it creates no new
 * items, it appends a revision to vocabulary cards the owner already has. It is
 * still a run rather than a separate concept because everything a run exists for
 * applies unchanged — a model was called, tokens were spent, output was validated,
 * per-item outcomes were counted, and the result needs a page the owner can read.
 * A parallel "enrichment run" table would duplicate all of that.
 */
export type GeneratedItemKind =
  "QUESTION" | "FLASHCARD" | "ENRICH_VOCABULARY" | "OBJECTIVE_IMPORT";

export const GENERATED_ITEM_KINDS: readonly GeneratedItemKind[] = [
  "QUESTION",
  "FLASHCARD",
  "ENRICH_VOCABULARY",
  "OBJECTIVE_IMPORT",
];

/**
 * Whether a run only *proposes* something the owner has still to confirm.
 *
 * `OBJECTIVE_IMPORT` is the only such kind so far, and it is the reason the run row
 * carries `proposedPayload` and `appliedAt`: a question run's output is in the bank
 * the moment the run completes, while an import run's output is a suggestion until
 * the owner applies it. A predicate rather than an equality check at each call site,
 * so the review screen, the repository, and the facade agree.
 */
export function proposesForConfirmation(kind: GeneratedItemKind): boolean {
  switch (kind) {
    case "QUESTION":
    case "FLASHCARD":
    case "ENRICH_VOCABULARY":
      return false;
    case "OBJECTIVE_IMPORT":
      return true;
  }
}

/**
 * Whether a run rewrites existing items rather than creating them.
 *
 * A predicate on the kind rather than a check spelled out at each call site, so
 * the review screen, the repository, and the facade agree about which runs own
 * their items and which only touched them.
 */
export function revisesExistingItems(kind: GeneratedItemKind): boolean {
  switch (kind) {
    case "QUESTION":
    case "FLASHCARD":
    // An import run touches no bank item at all: it proposes objectives, which are
    // the track's outline rather than its content.
    case "OBJECTIVE_IMPORT":
      return false;
    case "ENRICH_VOCABULARY":
      return true;
  }
}

/**
 * Run status.
 *
 * `PARTIAL` exists because a batch is not all-or-nothing: a model can return ten
 * items of which eight are usable, and discarding the eight would waste a call
 * the owner paid for while hiding that the other two were rejected. `FAILED`
 * covers both "the provider call failed" and "nothing survived validation".
 */
export type GenerationRunStatus =
  "PENDING" | "COMPLETED" | "PARTIAL" | "FAILED";

export const GENERATION_RUN_STATUSES: readonly GenerationRunStatus[] = [
  "PENDING",
  "COMPLETED",
  "PARTIAL",
  "FAILED",
];

/**
 * Token counts as reported by the provider, when it reports them.
 *
 * Deliberately narrow: only counts. Nothing derived from credentials, request
 * signing, or account identity may be stored in run metadata
 * (`SPEC.md` section 10.3).
 */
export interface ProviderUsage {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly totalTokens: number;
}

/**
 * Why a run failed, in owner-facing terms.
 *
 * A category rather than a provider message, because the provider's text can
 * carry account identifiers, request ids, and model payloads that must not reach
 * the interface or the log (`spec/SECURITY.md`).
 */
export type GenerationFailureCategory =
  | "PROVIDER_UNAVAILABLE"
  | "PROVIDER_THROTTLED"
  | "PROVIDER_REJECTED_REQUEST"
  | "NOT_AUTHORIZED"
  | "MODEL_ACCESS_DENIED"
  | "TIMED_OUT"
  | "MALFORMED_OUTPUT"
  | "NO_USABLE_ITEMS"
  | "UNEXPECTED";

export const GENERATION_FAILURE_CATEGORIES: readonly GenerationFailureCategory[] =
  [
    "PROVIDER_UNAVAILABLE",
    "PROVIDER_THROTTLED",
    "PROVIDER_REJECTED_REQUEST",
    "NOT_AUTHORIZED",
    "MODEL_ACCESS_DENIED",
    "TIMED_OUT",
    "MALFORMED_OUTPUT",
    "NO_USABLE_ITEMS",
    "UNEXPECTED",
  ];

export interface GenerationRun {
  readonly id: GenerationRunId;
  readonly certificationId: CertificationId;
  readonly itemKind: GeneratedItemKind;
  readonly generationMode: GenerationMode;
  readonly modelProvider: string;
  readonly modelId: string;
  readonly personaId: string;
  readonly personaVersion: number;
  readonly promptTemplateId: string;
  readonly promptTemplateVersion: number;
  /**
   * Fingerprint of the request that produced this run, so an equivalent batch
   * can be recognised before it is generated again (`SPEC.md` section 11.6).
   */
  readonly inputHash: string;
  /** Always empty in D6: model-knowledge generation has no sources. */
  readonly selectedSourceSnapshotIds: readonly string[];
  readonly requestedItemCount: number;
  readonly successfulItemCount: number;
  readonly failedItemCount: number;
  readonly usageMetadata: ProviderUsage | null;
  readonly failureReason: GenerationFailureCategory | null;
  /**
   * What an `OBJECTIVE_IMPORT` run proposed, as validated JSON text.
   *
   * Text rather than a parsed tree because this type is the run *record*: the run
   * knows it is carrying a proposal and how big it is, and the shape of the proposal
   * belongs to whatever kind of run made it. The application parses it through a
   * schema when it needs the tree (`objective-import.ts`), so a hand-edited row
   * fails loudly instead of reaching the objective hierarchy.
   *
   * `null` for every other kind, and for an import run that failed.
   */
  readonly proposedPayload: string | null;
  /**
   * When the proposal was applied, for the run kinds that have one.
   *
   * `null` means "not applied", which is the whole idempotence guard: a second apply
   * is refused by reading this column rather than by trusting the page that posted.
   */
  readonly appliedAt: IsoTimestamp | null;
  readonly startedAt: IsoTimestamp;
  readonly completedAt: IsoTimestamp | null;
  readonly status: GenerationRunStatus;
}

export function describeItemKind(kind: GeneratedItemKind): string {
  switch (kind) {
    case "QUESTION":
      return "Questions";
    case "FLASHCARD":
      return "Flashcards";
    case "ENRICH_VOCABULARY":
      return "Enriched vocabulary";
    case "OBJECTIVE_IMPORT":
      return "Imported objectives";
  }
}

export function describeItemKindSingular(kind: GeneratedItemKind): string {
  switch (kind) {
    case "QUESTION":
      return "question";
    case "FLASHCARD":
      return "flashcard";
    case "ENRICH_VOCABULARY":
      return "enriched card";
    case "OBJECTIVE_IMPORT":
      return "proposed objective";
  }
}

export function describeRunStatus(status: GenerationRunStatus): string {
  switch (status) {
    case "PENDING":
      return "In progress";
    case "COMPLETED":
      return "Completed";
    case "PARTIAL":
      return "Partly completed";
    case "FAILED":
      return "Failed";
  }
}

/**
 * Owner-facing explanation of a failure category.
 *
 * Every category has a sentence saying what to do about it, because a failed run
 * that only says "failed" leaves the owner guessing whether to retry, change the
 * request, or fix their configuration.
 */
export function describeFailureCategory(
  category: GenerationFailureCategory,
): string {
  switch (category) {
    case "PROVIDER_UNAVAILABLE":
      return "The model provider could not be reached. Check your network and try again.";
    case "PROVIDER_THROTTLED":
      return "The model provider is rate limiting requests. Wait a moment and try a smaller batch.";
    case "PROVIDER_REJECTED_REQUEST":
      return "The model provider rejected the request. Try a smaller batch or shorter instructions.";
    case "NOT_AUTHORIZED":
      return "The configured credentials were not accepted. Check the AWS profile or role this application runs with.";
    case "MODEL_ACCESS_DENIED":
      return "This account cannot use the configured model in this region. Request model access in the Bedrock console.";
    case "TIMED_OUT":
      return "The request took too long and was abandoned. Try a smaller batch.";
    case "MALFORMED_OUTPUT":
      return "The model did not return usable structured output, including after one repair attempt.";
    case "NO_USABLE_ITEMS":
      return "Every generated item failed validation, so nothing was saved.";
    case "UNEXPECTED":
      return "Generation stopped for an unexpected reason. Nothing was saved.";
  }
}

/**
 * The status a finished run should carry.
 *
 * One function so the run row, the review screen, and the tests cannot disagree
 * about what "partial" means.
 */
export function resolveRunStatus(counts: {
  readonly successfulItemCount: number;
  readonly failedItemCount: number;
}): Exclude<GenerationRunStatus, "PENDING"> {
  if (counts.successfulItemCount === 0) {
    return "FAILED";
  }

  return counts.failedItemCount === 0 ? "COMPLETED" : "PARTIAL";
}
